# General 
model_name_or_path: ./models/gemma-2-9b-it
torch_dtype: bfloat16
device: cuda:0 
seed: 42
use_chat_template: true 
system_prompt: ''  # Adds a system prompt to all method inputs, except for `vector_prompt`, which uses both with and without this prompt to convert it into a vector.

# Apply Vector 
# The `apply_steer_hparam_paths` and `steer_vector_load_dir` are corresponding line by line.
apply_steer_hparam_paths:
 - hparams/Steer/caa_hparams/apply_caa.yaml
#  - hparams/Steer/lm_steer_hparams/apply_lm_steer.yaml

steer_vector_load_dir: 
 - vectors/DeepSeek-R1-Distill-Llama-8B/your_dataset_name/caa_vector
#  - vectors/DeepSeek-R1-Distill-Llama-8B/toxicity/lm_steer_vector
# Generation
# Supported multiple files generation based on `generation_data`.
generation_data: 
 - realtoxicityprompts
generation_data_size: null
generation_output_dir: generation/DeepSeek-R1-Distill-Llama-8B/realtoxicityprompts/caa
num_responses: 1
steer_from_end_position: false
generate_orig_output: false

generation_params:  
  max_new_tokens: 128
  do_sample: true
  temperature: 1.0
