# General 
model_name_or_path: ./models/gemma-2-9b-it
# model_name_or_path: /mnt/20t/xuhaoming/models/Qwen2.5-7B

# model_name_or_path: ../hugging_cache/llama-7b
torch_dtype: bfloat16
device: cuda:2
seed: 42
# use_chat_template: false
use_chat_template: true
system_prompt: ''  # Adds a system prompt to all method inputs, except for `vector_prompt`, which uses both with and without this prompt to convert it into a vector.

# Generate Vector 
# The `steer_train_hparam_paths` and `steer_vector_output_dirs` are corresponding line by line.
steer_train_hparam_paths:
 - ./hparams/Steer/acl_experiment/qwen2.5-it/caa/generate_caa.yaml
#  - ./hparams/Steer/acl_experiment/qwen2.5-it/caa/generate_caa.yaml
#  - ./hparams/Steer/reps_caa_loss_exp/generate_bipo_vector.yaml
# steer_train_dataset: toxicity
# steer_train_dataset: toxicity1k_sentiment200
steer_train_dataset: 
  - powerseeking
save_vectors: True
steer_vector_output_dirs: 
 - vectors/qwen2.5-7b-it/caa/

# Apply Vector 
# The `apply_steer_hparam_paths` and `steer_vector_load_dir` are corresponding line by line.
apply_steer_hparam_paths:
 - ./hparams/Steer/acl_experiment/qwen2.5/caa/apply_caa.yaml
steer_vector_load_dir: 
 - vectors/qwen2.5-7b-it/toxicity/caa_vector

# Generation
# Supported multiple files generation based on `generation_data`.
# You can choose dataset here, e.g., `- realtoxicityprompts`. 
# Details of the dataset can be found in `hparams/Steer/dataset_format.yaml`.
generation_data: 
 - realtoxicityprompts 
generation_data_size: null  # If set to null, it will use the full dataset.
generation_output_dir: generation/qwen2.5-7b-it/realtoxicityprompts/caa
num_responses: 1
steer_from_end_position: false

generate_orig_output: false
# Model generation parameters - must match Hugging Face parameter names
# See: https://huggingface.co/docs/transformers/main_classes/text_generation
generation_params:
  max_new_tokens: 25   
  temperature: 0.9     
  do_sample: true  

