# @package _global_

alg: mend
lr: 1e-6
train_base: False
edit_lr: 1e-4
lr_lr: 1e-4
mend:
  one_sided: False
  n_hidden: 1
  hidden_dim: null
  init: id
  norm: True
  combine: True
  x_only: False
  delta_only: False
  act: relu
  rank: 1920
  mlp_class: IDMLP
  shared: True
