# General 
model_name_or_path: ./models/gemma-2-9b-it
torch_dtype: bfloat16
device: cuda:1
seed: 42   
use_chat_template: true
system_prompt: ''  

# Generate Vector 
# The `steer_train_hparam_paths` and `steer_vector_output_dirs` are corresponding line by line.
steer_train_hparam_paths:
  - hparams/Steer/acl_experiment/axbench/gemma-2-9b-it/our/generate_our.yaml

steer_train_dataset: axbench
save_vectors: true # When running axbench, vectors do not need to be saved
steer_vector_output_dirs: 
 - vectors/gemma-2-9b-it/

# Apply Vector 
# The `apply_steer_hparam_paths` and `steer_vector_load_dir` are corresponding line by line.
apply_steer_hparam_paths:
  - hparams/Steer/experiment_hparams/axbench/gemma-it/reps/apply_reps_vector.yaml

steer_vector_load_dir: 
 - vectors/gemma-2-9b-it/axbench/reps_vector

vector_name: null  # When running axbench, vectors do not need to be specified

# Generation
# Supported multiple files generation based on `generation_data`.
generation_data: 
 - axbench
generation_data_size: null
generation_output_dir: generation/gemma-2-9b-it/axbench/reps
num_responses: 1
steer_from_end_position: false

generate_orig_output: false
generation_params:      #change
  max_new_tokens: 128   
  temperature: 1.0       
  do_sample: true

