name: bert-base-uncased
class_name: BertClassifier
tokenizer_class: BertTokenizerFast
tokenizer_name: bert-base-uncased
inner_params:
- model.encoder.layer.9.intermediate.dense.weight
- model.encoder.layer.9.output.dense.weight
- model.encoder.layer.10.intermediate.dense.weight
- model.encoder.layer.10.output.dense.weight
- model.encoder.layer.11.intermediate.dense.weight
- model.encoder.layer.11.output.dense.weight

pt: ${hydra:runtime.cwd}/data/fever/FC_model.ckpt