name: google/t5-large-ssm-nq
class_name: AutoModelForSeq2SeqLM
tokenizer_class: AutoTokenizer
tokenizer_name: google/t5-large-ssm-nq
inner_params:
- encoder.block.22.layer.1.DenseReluDense.wi.weight
- encoder.block.22.layer.1.DenseReluDense.wo.weight
- encoder.block.23.layer.1.DenseReluDense.wi.weight
- encoder.block.23.layer.1.DenseReluDense.wo.weight
- decoder.block.22.layer.2.DenseReluDense.wi.weight
- decoder.block.22.layer.2.DenseReluDense.wo.weight
- decoder.block.23.layer.2.DenseReluDense.wi.weight
- decoder.block.23.layer.2.DenseReluDense.wo.weight

pt: null